name: Build Master

on:
  push:
    branches:
    - master

permissions:
  contents: read
  id-token: write

jobs:
  deploy_nuget:
    runs-on: ubuntu-latest
    name: Deploy to NuGet
    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Build devcontainer
        run: docker build -t local ${{ github.workspace }}/.devcontainer

      - name: Set version
        run: echo "VER=6.3.${{ github.run_number }}" >> $GITHUB_ENV

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: bkoelman

      - name: Build
        run: >
          docker run -i
          -v $PWD:/srv
          -w /srv
          local
          /bin/bash -c "
          dotnet build -c Release -p:PackageVersion=$VER;
          dotnet nuget push **/*.nupkg
          -s 'https://api.nuget.org/v3/index.json'
          -k ${{ steps.login.outputs.NUGET_API_KEY }};
          "
